# -*- coding: utf-8 -*-
# (num, type, query, note)
# Renumerote sur voix.srt par renumerote.py — 159 plans.
# Les plans marques RETROUVE portent la narration que le master tronquait.
A = [
(1,"MOTION","","Chiffre 9 plein ecran, typo condensee, fond noir. Coupe seche sur le mot. Aucun clip."),
(2,"MOTION","","Compteur 1986 -> 2024 qui defile, puis 3 vignettes affiches qui claquent."),
(3,"CLIP","giant robot explosion city","Explosion generique, 3s max. Coupe sur le mot excellents."),
(4,"MOTION","","Titre de l'episode : TRANSFORMERS - LA FRANCHISE AU COMPLET. Board vide en fond."),
(5,"MOTION","","Le board S/A/B/D se dessine, cases vides. C'est le visuel signature de la chaine."),
(6,"PHOTO","","Affiche floutee d'un film non identifie, point d'interrogation par dessus."),
(7,"PHOTO","","Deuxieme affiche floutee. Les deux glissent vers des cases opposees du board."),
(8,"MOTION","","ON COMMENCE en gros. Transition vers la premiere fiche film."),

(9,"CLIP","one shall stand one shall fall","Fiche film 1986 en overlay coin haut gauche pendant tout le segment."),
(10,"CLIP","prepare for extermination","Plan d'ensemble de la bataille d'ouverture."),
(11,"CLIP","who are you Autobot","Sur cent episodes : montage rapide de 4 personnages non nommes, 1s chacun."),
(12,"CLIP","I don't know who that is","Plan long, laisser respirer."),
(13,"MOTION","","Trombinoscope de robots avec des noms qui apparaissent trop vite pour etre lus. Gag visuel."),
(14,"CLIP","Transformers 1986 animated battle","Le plus beau plan d'animation disponible. C'est l'argument."),
(15,"CLIP","Autobots transform and roll out 1986","Ralenti sur une transformation. Montrer la fluidite."),
(16,"CLIP","Optimus Prime arrives 1986","Montee de tension avant la mort. Baisser la musique."),
(17,"CLIP","do not grieve Optimus Prime dying","Le plan cle du segment. Ne pas couper trop tot."),
(18,"CLIP","do not grieve Optimus","Laisser le silence apres il meurt vite."),
(19,"PHOTO","","Photo d'archive : enfants devant une tele des annees 80. Ken Burns lent."),
(20,"MOTION","","Citation a l'ecran : UN FILM POUR VENDRE DES JOUETS. Typo machine a ecrire."),
(21,"PHOTO","","Photos de jouets Transformers G1 en boite, vintage."),
(22,"CLIP","we are under attack retreat","Coupe plus nerveuse a partir d'ici, le montage doit imiter le propos."),
(23,"CLIP","Autobots attack Decepticons 1986","5 micro-plans de 1s : bataille / poursuite / bataille / nouveau perso / bataille."),
(24,"MOTION","","Chrono 80 MINUTES qui defile a toute vitesse."),
(25,"CLIP","Hot Rod","Plan de Hot Rod, puis fondu au gris pour illustrer le vide."),
(26,"CLIP","Unicron","Le plan le plus large possible d'Unicron."),
(27,"PHOTO","","Portrait d'Orson Welles + carton ORSON WELLES, 1985, DERNIER ROLE."),
(28,"MOTION","","Recap 3 points : COURT / ENERGIQUE / IMPORTANT, en liste."),
(29,"MOTION","","VERDICT B. La vignette du film glisse dans la case B du board. Son de claquement."),
(30,"MOTION","","2007 plein ecran. Rupture de rythme totale avec ce qui precede."),
(31,"MOTION","","L AFFICHE 2007 tenue en grand, Ken Burns lent, avec un bandeau MICHAEL BAY / REALISATEUR. Pas de photo de lui : la seule libre est en CC BY-SA, qui obligerait a crediter dans la description de la video."),
(32,"CLIP","I am Optimus Prime","Plan large heroique."),
(33,"CLIP","Optimus Prime transformation 2007","Le plan de reference pour parler des VFX."),
(34,"MOTION","","Ralenti 50% sur les pieces qui bougent. Zoom progressif. CE PLAN N EST PAS UN EXTRAIT. Apres huit formulations en 2 campagnes : Clip.cafe n a aucun plan de transformation pour ce film. Les 11 clips du segment 2007 sont tous des repliques — le catalogue est indexe sur les dialogues, un plan muet n y entre pas. A faire en motion : les mots PLAQUES / PIVOTS / VIS qui s emboitent, ou un bout du plan 033 rejoue au ralenti."),
(35,"MOTION","","Encart chiffre : 40 TONNES, avec fleches de poids sur le robot."),
(36,"CLIP","something is coming","Plan d'attente, tension."),
(37,"CLIP","Blackout attacks base","Traiter comme du film d'horreur : plans courts, noir entre les plans."),
(38,"CLIP","are you LadiesMan217","Barricade dans le stationnement. Plan de poursuite."),
(39,"CLIP","my name is Optimus Prime","L'arrivee. Plan le plus large disponible."),
(40,"CLIP","freedom is the right of all sentient beings","Continuite du plan precedent, laisser finir la replique."),
(41,"MOTION","","Colonne DEFAUTS qui s'ouvre a droite du cadre. Change le registre visuel."),
(42,"CLIP","soldiers Qatar base attack","Plan du groupe de soldats, visages flous sauf un."),
(43,"CLIP","Sam Witwicky parents scene","Plan de blague datee, 2s, coupe rapide, sans commentaire."),
(44,"CLIP","the car stands up","Le plan fondateur : la voiture qui se leve. Plan long."),
(45,"MOTION","","RETROUVE. Citation a l'ecran : C'EST SIMPLE, C'EST UNIVERSEL. Typo machine a ecrire. Cette phrase n'existait pas dans l'ancien montage."),
(46,"MOTION","","VERDICT A. Transformers 2007. RETROUVE — la phrase du verdict etait coupee. La vignette glisse dans la case A, puis le wipe part sur « Deux ans plus tard, tout part en fumee »."),
(47,"MOTION","","RETROUVE. Wipe arc-en-ciel, puis la fiche film REVENGE OF THE FALLEN 2009 en plein ecran. Bandeau : greve des scenaristes 2007-2008."),
(48,"MOTION","","Six lignes de titres qui s'empilent a l'ecran, illisibles a la fin. Illustre le chaos."),
(49,"CLIP","Sam goes to college","3 plans de 2s : universite / couple / parents."),
(50,"CLIP","the machine will destroy the sun","Plan de la machine solaire."),
(51,"CLIP","The Fallen shall rise again","Plan de The Fallen. Puis carton 15 SECONDES avec chrono."),
(52,"CLIP","Bumblebee Sam argument","Plan de la dispute, coupe brutale au milieu d'une phrase."),
(53,"CLIP","falls from plane","Plan de chute. Gag de montage : coupe au noir."),
(54,"MOTION","","Les six lignes du plan 046 tombent hors cadre une par une."),
(55,"MOTION","","Carton L'HUMOUR, typo plus grosse que necessaire."),
(56,"CLIP","Revenge of the Fallen comedy scene","2s max, sans son."),
(57,"MOTION","","DEUX RAISONS, puis le chiffre 1 qui apparait."),
(58,"CLIP","forest battle Optimus Megatron Starscream","Le meilleur plan du film. Lui donner de la place."),
(59,"CLIP","Optimus fights three Decepticons forest","Plan large, pas de coupe pendant 3s."),
(60,"CLIP","Optimus forest fight wide shot","Souligner que la camera recule : choisir un plan large."),
(61,"MOTION","","Chiffre 2 qui apparait, meme animation que le 1."),
(62,"CLIP","Devastator climbs pyramid","Plan spectaculaire et bete assume."),
(63,"MOTION","","VERDICT D. Vignette dans la case D, en haut de la case."),
(64,"MOTION","","Fiche film Dark of the Moon. Transition plus posee."),
(65,"CLIP","Sentinel Prime pillars","Ambiance thriller : etalonnage plus froid sur ce segment."),
(66,"PHOTO","","Photos d'archive Apollo 11 + NASA. Traitement documentaire."),
(67,"CLIP","the dark side of the moon mission","Montage conspiration : documents, photos, plans de nuit."),
(68,"CLIP","Sam Witwicky job interview","Plan de Sam en costume, decale."),
(69,"CLIP","I saved the world twice","Plan de Sam qui rappelle ce qu'il a fait. Fusion de deux anciens plans : c'est celui qui ouvre le plan qui donne l'image."),
(70,"CLIP","I'm not going back for glory","Plan du dernier acte."),
(71,"CLIP","I am Sentinel Prime","Plan de presentation de Sentinel."),
(72,"CLIP","Sentinel Prime betrayal","Plan fixe, laisser la phrase respirer."),
(73,"CLIP","the needs of Cybertron outweigh","Le plan qui porte l'argument de logique."),
(74,"CLIP","Chicago battle Decepticons","Debut de la sequence Chicago."),
(75,"MOTION","","Encart 45 MINUTES + mini plan de Chicago avec zones d'action."),
(76,"CLIP","the building is coming down get out","Le plan de l'edifice qui s'effondre. Plan le plus long du segment."),
(77,"CLIP","Carly Spencer scene","Plan de Carly, neutre, sans emphase."),
(78,"CLIP","Ironhide dies","Plan de la mort d'Ironhide, coupe volontairement trop tot. Le texte dit « la digerer » — l'ancien SRT avait transcrit « l'exagerer »."),
(79,"MOTION","","VERDICT A. Dark of the Moon. RETROUVE. Vignette dans la case A sous Transformers 2007, puis le wipe part sur « Et ensuite, le vide »."),
(80,"MOTION","","RETROUVE. Fiche film AGE OF EXTINCTION 2014 en plein ecran, puis le chiffre 2 H 45 qui s'ecrase par-dessus : plus long que la majorite des films primes."),
(81,"CLIP","hunting Transformers KSI","Plan de chasse aux Transformers."),
(82,"CLIP","we build our own Transformers","Plan de l'usine KSI."),
(83,"MOTION","","Deux bonnes idees affichees puis barrees d'un trait."),
(84,"CLIP","Lockdown bounty hunter","Plan de Lockdown, isole du reste."),
(85,"CLIP","Lockdown bounty hunter","Plan de Lockdown, isole du reste."),
(86,"CLIP","Cade Yeager inventor","Plan de Cade dans son atelier."),
(87,"CLIP","Tessa Yeager in danger","Plan de Tessa, puis transition vers Ratchet."),
(88,"CLIP","Ratchet dies","Le plan qui porte l'emotion du segment. Chrono 90 SECONDES en surimpression."),
(89,"MOTION","","Colonne POINTS POSITIFS qui s'ouvre, comme au plan 041."),
(90,"CLIP","Age of Extinction desert","Plan d'ambiance poussiereuse. Etalonnage chaud."),
(91,"CLIP","Optimus Prime I will kill you","Plan d'Optimus amer."),
(92,"CLIP","Optimus rides Grimlock","Le plan iconique. Plan long, plein ecran."),
(93,"MOTION","","VERDICT D. Vignette dans la case D, sous Revenge of the Fallen."),
(94,"CLIP","King Arthur knights dragon","Plan de l'ouverture medievale."),
(95,"CLIP","transforming dragon Merlin","Plan du dragon. Puis chrono 10 MINUTES."),
(96,"MOTION","","Demonstration du changement de ratio : le cadre change de format a l'ecran, 4 fois."),
(97,"CLIP","Optimus Prime Nemesis Prime","Plan d'Optimus sous controle mental."),
(98,"MOTION","","Frise chronologique de la mythologie qui se reecrit et s'efface."),
(99,"CLIP","Earth is Unicron","Plan de la revelation. NOTE : le SRT ecrit un icron, corriger en Unicron."),
(100,"CLIP","The Last Knight battle","Plan bruyant et confus, assume."),
(101,"CLIP","Quintessa","Plan de Quintessa."),
(102,"CLIP","I am Quintessa","Plan fixe, court, comme le personnage."),
(103,"CLIP","Anthony Hopkins Cogman","Plan de Hopkins et Cogman. Le seul moment chaleureux du segment."),
(104,"MOTION","","Comparatif deux colonnes : ENNUYEUX vs INCOHERENT."),
(105,"MOTION","","Les vignettes des films aimes se fissurent. Illustre la destruction retroactive."),
(106,"MOTION","","VERDICT D. Vignette tout en bas de la case D. Board complet a l'ecran 2s."),
(107,"MOTION","","Carton commentaires. Changement de fond, respiration visuelle."),
(108,"MOTION","","Animation d'abonnement, puis ON CONTINUE et retour au board."),
(109,"CLIP","Cybertron battle Bumblebee opening","Plan de la bataille sur Cybertron."),
(110,"CLIP","Optimus Prime Cybertron battle","Plans de designs classiques G1. Montage plus genereux ici."),
(111,"CLIP","Optimus Prime Cybertron battle","Plans de designs classiques G1. Montage plus genereux ici."),
(112,"CLIP","Bumblebee escape pod","Transition vers la Terre."),
(113,"MOTION","","Schema d'echelle : les autres films en grand, Bumblebee en petit et centre."),
(114,"CLIP","Charlie Watson garage","Plan de presentation de Charlie."),
(115,"CLIP","Charlie diving board","Plan du plongeoir. Le plus important du segment."),
(116,"CLIP","Charlie fixing the car","Plan de reparation, sans dialogue."),
(117,"CLIP","Charlie dives","Le plan d'aboutissement. Plan long, musique."),
(118,"CLIP","Bumblebee cannot speak radio voice","Plan de Bumblebee brise."),
(119,"CLIP","Bumblebee radio voice","Plan de la relation, chaleureux."),
(120,"CLIP","Bumblebee fight Shatter","Plan d'action lisible, contraste avec les films Bay."),
(121,"CLIP","Bumblebee outsmarts Decepticons","Plan de ruse."),
(122,"MOTION","","VERDICT S. Vignette seule dans la case S. Le moment fort du board."),
(123,"MOTION","","Courbe de qualite du film : haut, creux, haut. Graphique simple."),
(124,"CLIP","Maximals Rise of the Beasts","Plan d'ouverture."),
(125,"CLIP","transwarp key","4 plans de 1.5s : Maximals / cle / Unicron / Scourge."),
(126,"CLIP","Scourge Rise of the Beasts","Plan de Scourge, imposant."),
(127,"MOTION","","Le graphique du plan 120 s'effondre. Un seul mot : PEROU."),
(128,"CLIP","temple Peru exposition","Plan d'exposition, volontairement statique."),
(129,"MOTION","","Chrono 40 MINUTES qui tourne dans le vide."),
(130,"CLIP","Noah Diaz brother","Plan de Noah et son frere."),
(131,"CLIP","Elena artifact museum","Plan d'Elena. Puis transition, la courbe remonte."),
(132,"CLIP","final battle Rise of the Beasts","Plan de la bataille finale."),
(133,"CLIP","Bumblebee returns","Le retour de Bumblebee. Plan de payoff."),
(134,"MOTION","","VERDICT B. Vignette dans la case B, sous le film de 1986."),
(135,"MOTION","","Carton ET ON TERMINE SUR UNE SURPRISE."),
(136,"MOTION","","COLONNE des reproches, une ligne par grief au rythme de la phrase : TON TROP ENFANTIN / ANIMATION ETRANGE / CONCEPT CONDAMNE D AVANCE. Seule la colonne contre se remplit ; la colonne pour reste vide jusqu au plan 138, qui la renverse. Aucun nombre de dislikes a l ecran : YouTube ne les montre plus depuis 2021, et un nombre invente n est pas une source."),
(137,"PHOTO","","Commentaires YouTube negatifs de l'epoque, defilement vertical."),
(138,"CLIP","Transformers One animation","Renversement : plan superbe, plein ecran, silence."),
(139,"CLIP","Orion Pax D-16","Plans d'animation expressive."),
(140,"CLIP","Transformers One transformation","Ralenti sur une transformation. Rappel direct du plan 034."),
(141,"CLIP","Orion Pax and D-16 friendship","Plan de la relation centrale."),
(142,"CLIP","D-16 becomes Megatron","Le basculement. Plan long."),
(143,"CLIP","Sentinel Prime betrayal Transformers One","Plan de l'injustice partagee."),
(144,"MOTION","","Split screen : les deux visages, l'un s'assombrit progressivement."),
(145,"MOTION","","Colonne DEFAUTS, meme animation que 041 et 087."),
(146,"CLIP","we are brothers Transformers One","Plan de dialogue surexplique, 3s."),
(147,"CLIP","Transformers One wide shot","Plan de mise en scene qui se suffit. Sans dialogue."),
(148,"CLIP","Optimus Prime Megatron Transformers One","Plan final du segment."),
(149,"MOTION","","VERDICT A. Vignette dans la case A. Puis dezoom sur le board complet."),
(150,"MOTION","","Board complet. La case S s'illumine, Bumblebee seul."),
(151,"MOTION","","Zoom sur la vignette Bumblebee, le reste s'assombrit."),
(152,"MOTION","","La case A s'illumine, ses 3 vignettes."),
(153,"MOTION","","La case B s'illumine, ses 2 vignettes."),
(154,"MOTION","","La case D s'illumine. The Last Knight clignote en dernier."),
(155,"MOTION","","Chiffres 9 FILMS / 40 ANS, rappel du plan 001. Boucle fermee."),
(156,"CLIP","Unicron planet devours","Montage de ce qui ne marche pas : chevaliers, lignees, planetes."),
(157,"CLIP","Charlie and Bumblebee","Retour a l'image simple. Contraste avec le plan precedent."),
(158,"MOTION","","Vignette Age of Extinction seule a l'ecran, avec un point d'interrogation."),
(159,"MOTION","","Carte de fin : prochaine tier list + abonnement. Board en fond."),
]
